HTML+CSS+JS/Background/Parallax-Effect/README.md
HTML+CSS+JS/Background/Parallax-Effect/index.html
HTML+CSS+JS/Background/Parallax-Effect/style.css
HTML+CSS+JS/README.md

Added Parallax effect background in Backgrounds
closes: #17 
On my local server
-   [x] I'm Hacktoberfest'21 contributor.
-   [x] I have …

Parallax Effect Background

---

HTML+CSS+JS/Loader/Bar-Loader/README.md
HTML+CSS+JS/Loader/Bar-Loader/index.html
HTML+CSS+JS/Loader/Bar-Loader/style.css
HTML+CSS+JS/README.md

I added a bar loader with glow on each bar
closes: #38 
-   [x] I'm Hacktoberfest'21 contributor.
-   [x] I have commented my code, …

Added bar loader

---

HTML+CSS+JS/Navigation-Bar/Side-Navigation-Bar/README.md
HTML+CSS+JS/Navigation-Bar/Side-Navigation-Bar/index.html
HTML+CSS+JS/Navigation-Bar/Side-Navigation-Bar/style.css
HTML+CSS+JS/README.md

I have added a side navigation bar to the repository
closes: #43 
-   [x] I'm Hacktoberfest'21 contributor.
-   [x] I have commented my …

Added Side Navbar

---

HTML+CSS+JS/Footer/animated-social-media-links/index.css
HTML+CSS+JS/Footer/animated-social-media-links/index.html
HTML+CSS+JS/Footer/animated-social-media-links/readme.md
HTML+CSS+JS/README.md

Added animated-social-media-links in Footer directory and updated the component in the main readme file.
closes: #67 
Tested using VS Code Live Server Preview and Chrome and Firefox web browsers.
-   [x] Have you formatted your code ? (You can use any html,css …

Added animated-social-media-links component in Footer directory

---

HTML+CSS+JS/Buttons/Shiny-Button/README.md
HTML+CSS+JS/Buttons/Shiny-Button/index.html
HTML+CSS+JS/Buttons/Shiny-Button/style.css
HTML+CSS+JS/README.md

I added the shiny button animation.
closes: #73 
-   [x] I'm Hacktoberfest'21 contributor.
-   [x] I have commented my code, particularly …

Added shiny button

---

HTML+CSS+JS/Buttons/glowing-animated-button/index.css
HTML+CSS+JS/Buttons/glowing-animated-button/index.html
HTML+CSS+JS/Buttons/glowing-animated-button/readme.md
HTML+CSS+JS/README.md

Added glowing-animated-button folder in Buttons directory. It contains the files: index.html, index.css and readme.md.
closes: #46 
Tested using VS Code Live Server Preview and Chrome and Firefox web browsers.
-   [x] Have you formatted your code ? (You can …

Added glowing-animated-button in Buttons directory

---

HTML+CSS+JS/Footer/multilevel-footer/README.md
HTML+CSS+JS/Footer/multilevel-footer/index.html
HTML+CSS+JS/Footer/multilevel-footer/styles.css
HTML+CSS+JS/README.md

Added multi level footer in Footer directory. Contains index.html, styles.css and README.md.
closes: #96
It was tested using VS code live server
-   [x] Have you formatted your code ? (You can use any html, css beautifier)
-   [x] My changes generates no new …

Added Multilevel Footer

---

embellish-website/css/styles.css
embellish-website/include/navbar.html
embellish-website/index.html

Modified a few elements to enhance responsiveness
closes: #227 
Remove this line and tell us how the code was tested.
-   [ ] Have you made corresponding changes to the documentation?
-   [x] I'm …

responsiveness

---

embellish-website/css/styles.css
embellish-website/index.html

Fixed the component that was causing the responsiveness to break through css classes.
Closes: #233
It was tested for various device resolutions available on Chrome Dev Tools.
-   [x] …

Improved responsiveness

---

embellish-website/js/component.js

Changed the location in the component.js script file
closes: #235
By looking up the website in browser's dev tools 
-   [x] I'm Diversion …

Fixed Component Rendering

---

embellish-website/js/componentData.json

Changed dead links in Components.json file 
closes: #237 
-   [ ] Have you made corresponding changes to the documentation?
-   [ ] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] I'm OpenCode contributor.
-   [ ] I have commented my code, …

FIxed broken links in components

---

embellish-website/about.html
embellish-website/include/navbar.html

Fixed Incorrect Spelling
~~Contributers~~ - Contributors
~~Comtributing~~ - Contributing
Some changes shown are just formatted with Prettier.
closes: #239 
No Test Required: Incorrect Spelling
-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIBUTING.md) while contributing.
-   [x] I'm Diversion contributor.
-   [x] I …

239 fixed incorrect spelling

---

embellish-website/css/styles.css
embellish-website/index.html

the position for more components button was fixed for mobile view
closes: #238 
Using chrome dev tools are running website on live server …

more components button fix resolves #238

---

embellish-website/css/styles.css
embellish-website/index.html
embellish-website/js/component.js

Fixed the margin issue for more components button on desktop view
closes: #244 
Running code on local server.
-   [ ] I'm OpenCode …

fixed margin for more component button resolves #244

---

embellish-website/include/footer.html

Removed Privacy and terms instead of that I've added about us and components with their links.
closes: #246

Updated footer links

---

HTML+CSS+JS/Footer/Glowing-icons-with-hover/README.md
HTML+CSS+JS/Footer/Glowing-icons-with-hover/index.html
HTML+CSS+JS/Footer/Glowing-icons-with-hover/style.css
HTML+CSS+JS/README.md
embellish-website/js/componentData.json

added glowing icons with hover effect.
closes: #260 
I hv tested it on my local system.
-   [ ] I have …

added glowing icons with hover

---

HTML+CSS+JS/Loader/liquid-loading-animation/README.md
HTML+CSS+JS/Loader/liquid-loading-animation/index.html
HTML+CSS+JS/Loader/liquid-loading-animation/style.css
embellish-website/js/componentData.json

Added a liquid loader animation
closes: #259 
I hv run the code on my system.
-   [ ] I have commented my …

liquid loading animation

---

HTML+CSS+JS/Cards/Drag_&_Drop_Card/README.md
HTML+CSS+JS/Cards/Drag_&_Drop_Card/index.html
HTML+CSS+JS/Cards/Drag_&_Drop_Card/style.css
HTML+CSS+JS/README.md
embellish-website/js/componentData.json

A Simple drag & drop card which uses Sortable Library.
closes: #273 
In VScode
Add here the GIF you created.
https://user-images.githubusercontent.com/73753957/180600711-78 …

Drag & Drop Card Added

---

HTML+CSS+JS/Mouse Hover Effects/Day-Night-Hover-Effect/README.md
HTML+CSS+JS/Mouse Hover Effects/Day-Night-Hover-Effect/index.html
HTML+CSS+JS/Mouse Hover Effects/Day-Night-Hover-Effect/style.css
HTML+CSS+JS/README.md
README.md
embellish-website/js/componentData.json

Hover effect with the use of nth child
closes: #275 
In VsCode
Add here the GIF you created.
https://user-images.githubusercontent.com/73753957/180636870-9b0aae12-e3a5-4fa4 …

Day Night Hover effect Added

---

embellish-website/css/styles.css

Add a hover effect on navigation links
closes: #283
Tested on chrome browser.
-   [ ] Have you made corresponding changes to the documentation?
-   [ ] Have you formatted your code ? (You can use any html,css beautifier)
-   [x] I have commented my …

Add a hover effect on navigation links

---

HTML+CSS+JS/Forms/Login-Form/README.md
HTML+CSS+JS/Forms/Login-Form/index.html
HTML+CSS+JS/Forms/Login-Form/style.css
HTML+CSS+JS/README.md
embellish-website/js/componentData.json

Added login Page.
closes: #293 
It was tested on VS code.
-   [x] I have commented my code, particularly …

Added Login Form

---

HTML+CSS+JS/Cards/Flipping-Cards/README.md
HTML+CSS+JS/Cards/Flipping-Cards/index.html
HTML+CSS+JS/Cards/Flipping-Cards/style.css
HTML+CSS+JS/README.md
embellish-website/js/componentData.json

Added Flipping Card.
closes: #305 
It is tested on VS code.
-   [x] I have commented my code, …

Added Flipping Card

---

embellish-website/css/styles.css

Added some styling to the scroll bar
closes: #317 
it's tested in my local machine
-   [ ] Have you made corresponding changes to the documentation?
-   [x] I'm Diversion2k23 contributor.
-   [x] I have …

Added style to the scroll bar

---

embellish-website/css/styles.css
embellish-website/index.html

Added Hover style on Get started button
closes: #318 
-   [x] I'm Diversion2k23 contributor.
-   [x] I have commented my code, …

Added Hover style on Get Started button #318

---

HTML+CSS+JS/Navigation-Bar/Circular_Nav_Menu/README.md
HTML+CSS+JS/Navigation-Bar/Circular_Nav_Menu/index.html
HTML+CSS+JS/Navigation-Bar/Circular_Nav_Menu/script.js
HTML+CSS+JS/Navigation-Bar/Circular_Nav_Menu/styles.css
HTML+CSS+JS/README.md
embellish-website/js/componentData.json

I have added a new component namely:- Circular_Nav_Menu, under the Navigation-Bar folder.
closes: #344 
Remove this line and tell us how the code was tested.
-   [x] My changes …

Added Circular_Nav_Menu 

---

HTML+CSS+JS/Modal/Upload_Modal/README.md
HTML+CSS+JS/Modal/Upload_Modal/index.html
HTML+CSS+JS/Modal/Upload_Modal/script.js
HTML+CSS+JS/Modal/Upload_Modal/styles.css
HTML+CSS+JS/README.md
embellish-website/js/componentData.json

I have added an uploading modal that is fully functional and can be used on any of the websites that require the user to give info in the form of a pic, pdf, etc.
closes: #351 
Remove this line and tell us how the code was tested.
-   [x] Have you formatted …

Upload_Modal 

---

embellish-website/css/styles.css
embellish-website/index.html

1)Removed the box shadow part as it doesn't match the styling of other sections of the website
2) Increased the font weight of the 'Our Components' title, such that it could look the same as the rest of the sections of the website.
3) Removed the Uppercase as this has not been followed in any sections and it looks out of context in a single place.
4) Aligned the text below 'Our Components' to the center.
5) Gave margin-bottom to the 'components you may like' section heading.
closes: #354 
Remove this line and tell us how the code was tested.
-   [x] Have you followed the [Contribution Guidelines](https://github.com/siddhi-244/Embellish/blob/46893695e5f28da0b0f928ae614b262239351d31/CONTRIB …

Updated Our Components section 

---

embellish-website/css/styles.css

closes: #360 
-   [x] I'm Diversion2k23 contributor.
-   [x] I have commented my code, particularly in hard-to-understand areas.

Fixed text not visible in dark mode
